In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])

print(x.__class__)
print(x.shape)
print(x.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [5]:
W = np.array([[1, 2, 3],
              [4, 5, 6]])
print(W.ndim)
print(W.shape)

2
(2, 3)


In [6]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])

print(W + X)
print('---')
print(W * X)  # 아다마르 곱(Hadamard product)

[[ 1  3  5]
 [ 7  9 11]]
---
[[ 0  2  6]
 [12 20 30]]


In [9]:
# 벡터의 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
y = np.dot(a, b)
print(y)

# 행렬곱
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
Y = np.dot(A, B)
print(Y)

32
[[19 22]
 [43 50]]


In [11]:
# 벡터의 내적
y = a @ b
print(y)

# 행렬곱
Y = A @ B
print(Y)

32
[[19 22]
 [43 50]]
