In [1]:
import torch
import torch.nn as nn

In [2]:
W = nn.Parameter(torch.zeros(1, 1))
b = nn.Parameter(torch.zeros(1))

print(W)
print(b)

Parameter containing:
tensor([[0.]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [5]:
class Model(nn.Module):  # Module 클래스 상속
  def __init__(self):
    super().__init__()
    self.W = nn.Parameter(torch.zeros(1, 1))
    self.b = nn.Parameter(torch.zeros(1))

  def forward(self, x):
    y = x @ self.W + self.b
    return y

model = Model()

# 모델의 모든 매개변수에 접근할 수 있음
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[0.]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [18]:
class Model(nn.Module):
  def __init__(self, input_size=1, output_size=1):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)  # Linear 클래스 사용

  def forward(self, x):
    y = self.linear(x)  # 앞에서는 y = x @ self.W + self.b
    return y

model = Model()
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[0.5245]], requires_grad=True)
Parameter containing:
tensor([0.7814], requires_grad=True)


In [21]:
# 옵티마이저

# 토이 데이터셋
x = torch.rand(100, 1)
y = 5 + 2 * x + torch.rand(100, 1)

lr = 0.1
iters = 100

model = Model()
optimizer = torch.optim.SGD(model.parameters(), lr=lr)  # 옵티마이저 생성

for i in range(iters):
  y_hat = model(x)
  loss = nn.functional.mse_loss(y, y_hat)

  loss.backward()
  optimizer.step()       # 매개변수 갱신
  optimizer.zero_grad()  # 기울기 재설정